spring.application.name=receipt-ocr
server.port=3000
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.show-actuator=true
spring.datasource.url=jdbc:postgresql://localhost:5432/app
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
jwt.secret=${JWT_SECRET}
# spring.docker.compose.enabled=false
